import type { ExpenseCategory, LocationProfile } from "./types";

export const MODEL_VERSION = "demo_v0_1_six_city_fixture";

export const DATA_VINTAGE = {
  taxes: "Demo simplified 2026-style W-2 tax curves, not PolicyEngine",
  housing: "Temporary fixture shaped like HUD FMR 1BR data",
  prices: "Temporary fixture shaped like BEA RPP category indices",
  geography: "Temporary six-place fixture with county/metro labels",
};

export const NATIONAL_BASELINE_EXPENSES: Record<
  Exclude<ExpenseCategory, "housing" | "other_nonhousing">,
  number
> = {
  food: 8_400,
  transportation: 10_200,
  healthcare: 6_600,
  internet_mobile: 1_800,
};

export const OTHER_BASELINE_EXPENSE = 18_000;
export const DISCRETIONARY_GROSS_SHARE = 0.08;

export const DEMO_LOCATIONS: LocationProfile[] = [
  {
    id: "PLACE:4845700",
    displayName: "Austin, TX",
    shortName: "Austin",
    countyName: "Travis County",
    state: "TX",
    stateName: "Texas",
    cbsaName: "Austin-Round Rock-Georgetown, TX",
    computationLocationId: "COUNTY:48453",
    lat: 30.2672,
    lon: -97.7431,
    mapX: 47,
    mapY: 72,
    annualRent1Br: 18_000,
    priceIndex: {
      food: 96,
      transportation: 97,
      healthcare: 94,
      internet_mobile: 98,
      other_nonhousing: 95,
    },
    confidence: "medium",
    notes: ["Texas has no state individual income tax in this simplified demo."],
  },
  {
    id: "PLACE:0677000",
    displayName: "Sunnyvale, CA",
    shortName: "Sunnyvale",
    countyName: "Santa Clara County",
    state: "CA",
    stateName: "California",
    cbsaName: "San Jose-Sunnyvale-Santa Clara, CA",
    computationLocationId: "COUNTY:06085",
    lat: 37.3688,
    lon: -122.0363,
    mapX: 13,
    mapY: 56,
    annualRent1Br: 47_400,
    priceIndex: {
      food: 127,
      transportation: 128,
      healthcare: 124,
      internet_mobile: 118,
      other_nonhousing: 132,
    },
    confidence: "medium",
    notes: ["California state income tax and SDI are approximated in this demo."],
  },
  {
    id: "PLACE:3651000",
    displayName: "New York, NY",
    shortName: "New York",
    countyName: "New York County",
    state: "NY",
    stateName: "New York",
    cbsaName: "New York-Newark-Jersey City, NY-NJ-PA",
    computationLocationId: "COUNTY:36061",
    lat: 40.7128,
    lon: -74.006,
    mapX: 88,
    mapY: 38,
    annualRent1Br: 45_600,
    priceIndex: {
      food: 122,
      transportation: 118,
      healthcare: 116,
      internet_mobile: 111,
      other_nonhousing: 124,
    },
    confidence: "medium",
    notes: ["NYC local income tax is approximated in this demo."],
  },
  {
    id: "PLACE:5363000",
    displayName: "Seattle, WA",
    shortName: "Seattle",
    countyName: "King County",
    state: "WA",
    stateName: "Washington",
    cbsaName: "Seattle-Tacoma-Bellevue, WA",
    computationLocationId: "COUNTY:53033",
    lat: 47.6062,
    lon: -122.3321,
    mapX: 16,
    mapY: 24,
    annualRent1Br: 31_800,
    priceIndex: {
      food: 116,
      transportation: 113,
      healthcare: 111,
      internet_mobile: 108,
      other_nonhousing: 115,
    },
    confidence: "medium",
    notes: ["Washington has no state individual income tax in this simplified demo."],
  },
  {
    id: "PLACE:0820000",
    displayName: "Denver, CO",
    shortName: "Denver",
    countyName: "Denver County",
    state: "CO",
    stateName: "Colorado",
    cbsaName: "Denver-Aurora-Lakewood, CO",
    computationLocationId: "COUNTY:08031",
    lat: 39.7392,
    lon: -104.9903,
    mapX: 41,
    mapY: 49,
    annualRent1Br: 22_800,
    priceIndex: {
      food: 104,
      transportation: 103,
      healthcare: 102,
      internet_mobile: 101,
      other_nonhousing: 105,
    },
    confidence: "medium",
    notes: ["Colorado flat income tax is approximated in this demo."],
  },
  {
    id: "PLACE:3755000",
    displayName: "Raleigh, NC",
    shortName: "Raleigh",
    countyName: "Wake County",
    state: "NC",
    stateName: "North Carolina",
    cbsaName: "Raleigh-Cary, NC",
    computationLocationId: "COUNTY:37183",
    lat: 35.7796,
    lon: -78.6382,
    mapX: 76,
    mapY: 59,
    annualRent1Br: 17_400,
    priceIndex: {
      food: 94,
      transportation: 92,
      healthcare: 93,
      internet_mobile: 96,
      other_nonhousing: 91,
    },
    confidence: "medium",
    notes: ["North Carolina flat income tax is approximated in this demo."],
  },
];

export const DEFAULT_SOURCE_ID = "PLACE:4845700";
export const DEFAULT_TARGET_ID = "PLACE:0677000";
export const DEFAULT_GROSS_INCOME = 175_000;
